---
abstract: 'A POE::Component::IRC plugin for IRC based DNSBL queries'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-IRC-Plugin-QueryDNSBL
requires:
  Net::IP: 0
  POE: 1.004
  POE::Component::Client::DNSBL: 0.06
  POE::Component::IRC: 5.7
  POE::Component::IRC::Common: 5.16
  POE::Component::IRC::Plugin: 0.1
  perl: v5.6.0
resources:
  homepage: http://github.com/bingos/poe-component-irc-plugin-querydnsbl/tree
  repository: git://github.com/bingos/poe-component-irc-plugin-querydnsbl.git
version: 1.02
